VideoShare/VideoShare/Controllers/AccountController.cs
using System;
using System.Globalization;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using Microsoft.AspNet.Identity.Owin;
using Microsoft.Owin.Security;
using VideoShare.Models;

namespace VideoShare.Controllers
{
    [Authorize]
    public class AccountController : Controller
    {
        private ApplicationSignInManager _signInManager;
        private ApplicationUserManager _userManager;

        public AccountController()
        {
        }

        public AccountController(ApplicationUserManager userManager, ApplicationSignInManager signInManager )
        {
            UserManager = userManager;
            SignInManager = signInManager;
        }

        public ApplicationSignInManager SignInManager
        {
            get
            {
                return _signInManager ?? HttpContext.GetOwinContext().Get<ApplicationSignInManager>();
            }
            private set 
            { 
                _signInManager = value; 
            }
        }

        public ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            private set
            {
                _userManager = value;
            }
        }

        //
        // GET: /Account/Login
        [AllowAnonymous]
        public ActionResult Login(string returnUrl)
        {
            ViewBag.ReturnUrl = returnUrl;
            return View();
        }

        //
        // POST: /Account/Login
        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Login(LoginViewModel model, string returnUrl)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            // This doesn't count login failures towards account lockout
            // To enable password failures to trigger account lockout, change to shouldLockout: true
            var result = await SignInManager.PasswordSignInAsync(model.Email, model.Password, model.RememberMe, shouldLockout: false);
            switch (result)
            {
                case SignInStatus.Success:
                    return RedirectToLocal(returnUrl);
                case SignInStatus.LockedOut:
                    return View("Lockout");
                case SignInStatus.RequiresVerification:
                    return RedirectToAction("SendCode", new { ReturnUrl = returnUrl, RememberMe = model.RememberMe });
                case SignInStatus.Failure:
                default:
                    ModelState.AddModelError("", "Invalid login attempt.");
                    return View(model);
            }
        }

        //
        // GET: /Account/VerifyCode
        [AllowAnonymous]
        public async Task<ActionResult> VerifyCode(string provider, string returnUrl, bool rememberMe)
        {
            // Require that the user has already logged in via username/password or external login
            if (!await SignInManager.HasBeenVerifiedAsync())
            {
                return View("Error");
            }
            return View(new VerifyCodeViewModel { Provider = provider, ReturnUrl = returnUrl, RememberMe = rememberMe });
        }

        //
        // POST: /Account/VerifyCode
        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> VerifyCode(VerifyCodeViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            // The following code protects for brute force attacks against the two factor codes. 
            // If a user enters incorrect codes for a specified amount of time then the user account 
            // will be locked out for a specified amount of time. 
            // You can configure the account lockout settings in IdentityConfig
            var result = await SignInManager.TwoFactorSignInAsync(model.Provider, model.Code, isPersistent:  model.RememberMe, rememberBrowser: model.RememberBrowser);
            switch (result)
            {
                case SignInStatus.Success:
                    return RedirectToLocal(model.ReturnUrl);
                case SignInStatus.LockedOut:
                    return View("Lockout");
                case SignInStatus.Failure:
                default:
                    ModelState.AddModelError("", "Invalid code.");
                    return View(model);
            }
        }

        //
        // GET: /Account/Register
        [AllowAnonymous]
        public ActionResult Register()
        {
            return View();
        }

        //
        // POST: /Account/Register
        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Register(RegisterViewModel model)
        {
            if (ModelState.IsValid)
            {
                var user = new ApplicationUser { UserName = model.Email, Email = model.Email };
                var result = await UserManager.CreateAsync(user, model.Password);

                if (result.Succeeded)
                {
                    var id = UserManager.FindByEmailAsync(model.Email);
                    var _result = await UserManager.AddToRoleAsync(id.Result.Id, "User");

                    await SignInManager.SignInAsync(user, isPersistent:false, rememberBrowser:false);

                    // For more information on how to enable account confirmation and password reset please visit https://go.microsoft.com/fwlink/?LinkID=320771
                    // Send an email with this link
                    // string code = await UserManager.GenerateEmailConfirmationTokenAsync(user.Id);
                    // var callbackUrl = Url.Action("ConfirmEmail", "Account", new { userId = user.Id, code = code }, protocol: Request.Url.Scheme);
                    // await UserManager.SendEmailAsync(user.Id, "Confirm your account", "Please confirm your account by clicking <a href=\"" + callbackUrl + "\">here</a>");

                    return RedirectToAction("Index", "Home");
                }
                AddErrors(result);
            }

            // If we got this far, something failed, redisplay form
            return View(model);
        }

        //
        // GET: /Account/ConfirmEmail
        [AllowAnonymous]
        public async Task<ActionResult> ConfirmEmail(string userId, string code)
        {
            if (userId == null || code == null)
            {
                return View("Error");
            }
            var result = await UserManager.ConfirmEmailAsync(userId, code);
            return View(result.Succeeded ? "ConfirmEmail" : "Error");
        }

        //
        // GET: /Account/ForgotPassword
        [AllowAnonymous]
        public ActionResult ForgotPassword()
        {
            return View();
        }

        //
        // POST: /Account/ForgotPassword
        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> ForgotPassword(ForgotPasswordViewModel model)
        {
            if (ModelState.IsValid)
            {
                var user = await UserManager.FindByNameAsync(model.Email);
                if (user == null || !(await UserManager.IsEmailConfirmedAsync(user.Id)))
                {
                    // Don't reveal that the user does not exist or is not confirmed
                    return View("ForgotPasswordConfirmation");
                }

                // For more information on how to enable account confirmation and password reset please visit https://go.microsoft.com/fwlink/?LinkID=320771
                // Send an email with this link
                // string code = await UserManager.GeneratePasswordResetTokenAsync(user.Id);
                // var callbackUrl = Url.Action("ResetPassword", "Account", new { userId = user.Id, code = code }, protocol: Request.Url.Scheme);		
                // await UserManager.SendEmailAsync(user.Id, "Reset Password", "Please reset your password by clicking <a href=\"" + callbackUrl + "\">here</a>");
                // return RedirectToAction("ForgotPasswordConfirmation", "Account");
            }

            // If we got this far, something failed, redisplay form
            return View(model);
        }

        //
        // GET: /Account/ForgotPasswordConfirmation
        [AllowAnonymous]
        public ActionResult ForgotPasswordConfirmation()
        {
            return View();
        }

        //
        // GET: /Account/ResetPassword
        [AllowAnonymous]
        public ActionResult ResetPassword(string code)
        {
            return code == null ? View("Error") : View();
        }

        //
        // POST: /Account/ResetPassword
        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> ResetPassword(ResetPasswordViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }
            var user = await UserManager.FindByNameAsync(model.Email);
            if (user == null)
            {
                // Don't reveal that the user does not exist
                return RedirectToAction("ResetPasswordConfirmation", "Account");
            }
            var result = await UserManager.ResetPasswordAsync(user.Id, model.Code, model.Password);
            if (result.Succeeded)
            {
                return RedirectToAction("ResetPasswordConfirmation", "Account");
            }
            AddErrors(result);
            return View();
        }

        //
        // GET: /Account/ResetPasswordConfirmation
        [AllowAnonymous]

VideoShare/VideoShare/Controllers/RoomController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using VideoShare.Models;

namespace VideoShare.Controllers
{
    [Authorize(Roles = "User, Admin")]
    public class RoomController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Room
        [Authorize(Roles = "Admin")]
        public async Task<ActionResult> Index()
        {
            return View(await db.RoomModels.ToListAsync());
        }

        // GET: Room/Details/5
        // Action allows controls of the Video Feed
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            RoomModels roomModels = await db.RoomModels.FindAsync(id);

            // User can only navigate to Details room page if they are the owner
            if (User.IsInRole("User") && User.Identity.Name != roomModels.RoomOwner)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            return View(roomModels);
        }

        // GET: Room/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Room/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "RoomID,RoomName,RoomCode,RoomUrl")] RoomModels roomModels)
        {
            // Room owner must be current logged in user
            roomModels.RoomOwner = User.Identity.Name;

            if (ModelState.IsValid)
            {
                db.RoomModels.Add(roomModels);
                await db.SaveChangesAsync();

                if (User.IsInRole("Admin"))
                    return RedirectToAction("Index");
                else
                    return RedirectToAction("Account", "User");
            }

            return View(roomModels);
        }

        // GET: Room/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            RoomModels roomModels = await db.RoomModels.FindAsync(id);
            if (roomModels == null)
            {
                return HttpNotFound();
            }

            if (User.IsInRole("User") && User.Identity.Name != roomModels.RoomOwner)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            return View(roomModels);
        }

        // POST: Room/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "RoomID,RoomName,RoomCode,RoomUrl")] RoomModels roomModels)
        {
            RoomModels roomModel = await db.RoomModels.FindAsync(roomModels.RoomID);

            if (User.IsInRole("User") && User.Identity.Name != roomModel.RoomOwner)
            {
                return new HttpStatusCodeResult(HttpStatusCode.Unauthorized);
            }
            
            if (ModelState.IsValid)
            {
                roomModel.RoomCode = roomModels.RoomCode;
                roomModel.RoomName = roomModels.RoomName;
                roomModel.RoomUrl = roomModels.RoomUrl;

                db.Entry(roomModel).State = EntityState.Modified;
                await db.SaveChangesAsync();

                if (User.IsInRole("Admin"))
                    return RedirectToAction("Index");
                else
                    return RedirectToAction("Account", "User");
            }
            return View(roomModels);
        }

        // GET: Room/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            RoomModels roomModels = await db.RoomModels.FindAsync(id);
            if (roomModels == null)
            {
                return HttpNotFound();
            }

            if (User.IsInRole("User") && User.Identity.Name != roomModels.RoomOwner)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            return View(roomModels);
        }

        // POST: Room/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            RoomModels roomModels = await db.RoomModels.FindAsync(id);

            if (User.IsInRole("User") && User.Identity.Name != roomModels.RoomOwner)
            {
                return new HttpStatusCodeResult(HttpStatusCode.Unauthorized);
            }

            db.RoomModels.Remove(roomModels);
            await db.SaveChangesAsync();

            if (User.IsInRole("Admin"))
                return RedirectToAction("Index");
            else
                return RedirectToAction("Account", "User");
        }

        public async Task<ActionResult> Lookup(string roomCode)
        {
            RoomModels roomModels = await db.RoomModels.
                FirstOrDefaultAsync(r => r.RoomCode == roomCode);

            if (roomModels == null)
            {
                return HttpNotFound();
            }
            
            return View(roomModels);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

VideoShare/VideoShare/Views/User/Account.cshtml
@model IEnumerable<VideoShare.Models.RoomModels>
<head>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
</head>

    @{
        ViewBag.Title = "Your Rooms - SIT";
    }

    <h2>Your Rooms</h2>

    <div>
        <dl class="dl-horizontal">
    
        </dl>
    </div>

<p>
    @Html.ActionLink("Create New", "../Room/Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.RoomName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.RoomCode)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.RoomUrl)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.RoomOwner)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.RoomName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.RoomCode)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.RoomUrl)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.RoomOwner)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", "Room", new { id = item.RoomID }, null) |
            @Html.ActionLink("Enter Room", "Details", "Room", new { id = item.RoomID }, null) |
            @Html.ActionLink("Delete", "Delete", "Room", new { id = item.RoomID }, null)
        </td>
    </tr>
    }
</table>

VideoShare/VideoShare/Views/User/Create.cshtml
@model VideoShare.Models.UserModels
<head>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
</head>

@{
    ViewBag.Title = "Create - SIT";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>UserModels</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.UserName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UserName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UserName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

VideoShare/VideoShare/Views/User/Delete.cshtml
@model VideoShare.Models.UserModels
<head>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
</head>

@{
    ViewBag.Title = "Delete - SIT";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>UserModels</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.UserName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UserName)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

VideoShare/VideoShare/Views/User/Details.cshtml
@model IEnumerable<VideoShare.Models.RoomModels>
<head>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
</head>

    @{
        ViewBag.Title = "Details - SIT";
    }

    <h2>Details</h2>

    <div>
        <h4>UserModels</h4>
        <hr />
        <dl class="dl-horizontal">
     
        </dl>
    </div>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.RoomName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.RoomCode)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.RoomUrl)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.RoomOwner)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.RoomID }) |
                @Html.ActionLink("Details", "Details", new { id = item.RoomID }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.RoomID })
            </td>
        </tr>
    }

    <p>
        @Html.ActionLink("Back to List", "Index")
    </p>

VideoShare/VideoShare/Views/User/Edit.cshtml
@model VideoShare.Models.UserModels
<head>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
</head>

@{
    ViewBag.Title = "Edit - SIT";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>UserModels</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.UserID)

        <div class="form-group">
            @Html.LabelFor(model => model.UserName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UserName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UserName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

VideoShare/VideoShare/Views/User/Index.cshtml
@model IEnumerable<VideoShare.Models.ApplicationUser>
<head>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
</head>

@{
    ViewBag.Title = "All Users - SIT";
}

<h2>All Users - Admin View</h2>

<table class="table">
    <tr>
        <th>
            User
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        if (item.Email != "Admin@email.com")
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Email)
                </td>
                <td>
                    @Html.ActionLink("Delete", "Delete", new { id = item.Id })
                </td>
            </tr>
        }

    }

</table>